from random import choice

extent_references = [
    ('Width of the milky way','{times:,.2f} times the width our galaxy, the Milky Way','1 / {fraction:,.0f} of the width our galaxy, the Milky Way'),
    ('Distance from the Sun to Neptune','{times:,.2f} times the distance from the Sun to Neptune','1 / {fraction:,.0f} of the distance from the Sun to Neptune'),
    ('Distance from the Earth to the Sun','{times:,.2f} times the distance from the Earth to the Sun','1 / {fraction:,.0f} of the distance from the Earth to the Sun'),
    ('Distance from the Earth to the Moon','{times:,.2f} times the distance from the Earth to the Moon','1 / {fraction:,.0f} of the distance from the Earth to the Moon'),
    ('Length of the equator','{times:,.2f} times the distance around the equator','1 / {fraction:,.0f} of the distance around the equator'),
    ('Distance from London to New York','{times:,.2f} times the distance from London to New York','1 / {fraction:,.0f} of the distance from London to New York'),
    ('Distance from London to Edinburgh','{times:,.2f} times the distance from London to Edinburgh','1 / {fraction:,.0f} of the distance from London to Edinburgh'),
    ('Altitude of the orbit of the International Space Station','{times:,.2f} times the height of the orbit of the International Space Station','1 / {fraction:,.0f} of the height of the orbit of the International Space Station'),
    ('Cruising altitude of Airbus commercial jet','{times:,.2f} times the cruising altitude of a commercial jet','1 / {fraction:,.0f} of the cruising altitude of a commercial jet'),
    ('Height of Mount Everest','{times:,.2f} times the height of Mount Everest','1 / {fraction:,.0f} of the height of Mount Everest'),
    ('Height of the Angel Falls (Venuzeula)','{times:,.2f} times the height of Angel Falls (Venuzeula)','1 / {fraction:,.0f} of the height of Angel Falls (Venuzeula)'),
    ('Height of the `Burj Khalifa` skyscraper (Dubai)','{times:,.2f} times the height of the `Burj Khalifa` scyscraper (Dubai)','1 / {fraction:,.0f} of the height of   the `Burj Khalifa` scyscraper (Dubai)'),
    ('Length of Tower Bridge over the Thames','{times:,.2f} times the length of London\'s Tower Bridge','1 / {fraction:,.0f} as long as London\'s Tower Bridge'),
    ('Length of a football pitch','{times:,.2f} football pitches end to end','1 / {fraction:,.0f} as long as a football pitch'),
    ('Length of a London bus','{times:,.2f} London buses end to end','1 / {fraction:,.0f} as long as a London bus'),
    ('Typical height of a giraffe','{times:,.2f} times the typical height of a giraffe','1 / {fraction:,.0f} of the typical height of a giraffe'),
    ('Height of an African elephant','{times:,.2f} times the height of an African elephant','1 / {fraction:,.0f} of the height of an African elephant'),
    ('Height of an ostrich','{times:,.2f} times the height of an ostrich','1 / {fraction:,.0f} of the height of an ostrich'),
    ('Length of an iPhone 6',"{times:,.2f} iPhone 6's end to end",'1 / {fraction:,.0f} as long as an iPhone 6'),
    ('Height of a standard Lego brick',"{times:,.2f} Lego bricks stacked",'1 / {fraction:,.0f} as high as a Lego brick'),
]

count_references = [
    ('Number of particles in a mole (Avogadro\'s number)','{times:,.2f} for every atom in a mole (every H atom in 1.008g of hydrogen)','One for every {fraction:,.0f} atoms in a mole (H atoms in 1.008g of hydrogen)'),
    ('Number of stars in the observable universe','{times:,.2f} for every star in the observable universe','One for every {fraction:,.0f} stars in the observable universe'),
    ('Number of grains of sand on the world\'s beaches','{times:,.2f} for every grain of sand on the world\'s beaches','One for every {fraction:,.0f} grains of sand on the world\'s beaches'),
    ('Number of bacteria in the human body','{times:,.2f} for every bacterium in the human body','One for every {fraction:,.0f} bacteria in the human body'),
    ('Number of synapses in the human brain','{times:,.2f} for every synapse in the human brain','One for every {fraction:,.0f} synapses in the human brain'),
    ('Number of fish in the sea','{times:,.2f} for every fish in the sea','One for every {fraction:,.0f} fish in the sea'),
    ('Number of stars in our galaxy','{times:,.2f} for every star in our galaxy','One for every {fraction:,.0f} stars in our galaxy'),
    ('Population of World','{times:,.2f} for every person in the world','One for every {fraction:,.0f} people in the world'),
    ('Population of China','{times:,.2f} for every person in China','One for every {fraction:,.0f} people in China'),
    ('Number of cars in the world','{times:,.2f} for every car in the world','One for every {fraction:,.0f} cars in the world'),
    ('Number of books in the British Library','{times:,.2f} for every book in the British Library','One for every {fraction:,.0f} books in the British Library'),
    ('Population of United States','{times:,.2f} for every person in the USA','One for every {fraction:,.0f} people in the USA'),
    ('Population of United Kingdom','{times:,.2f} for every person in the UK','One for every {fraction:,.0f} people in the UK'),
    ('Estimated world population of Horses','{times:,.2f} for every Horse in the world','One for every {fraction:,.0f} Horses in the world'),
    ('Number of grains of sugar in a cup','{times:,.2f} for every grain of sugar in a cup','One for every {fraction:,.0f} grains of sugar in a cup'),
    ('Number of strands on a head of hair','{times:,.2f} for every strand on a head of hair','One for every {fraction:,.0f} strands on a head of hair'),
    ('High estimate of world population of Lions','{times:,.2f} for every Lion in the world','One for every {fraction:,.0f} Lions in the world'),
    ('High estimate of world population of Tigers','{times:,.2f} for every Tiger in the world','One for every {fraction:,.0f} Tigers in the world'),
    ('Number of nuclear power plants in the world (2022)','{times:,.2f} for every nuclear power plant in the world','One for every {fraction:,.0f} nuclear power plants in the world'),
    ('Number of skyscrapers in New York City (>150m tall)','{times:,.2f} for every skyscraper in New York City','One for every {fraction:,.0f} skyscrapers in New York City'),
]

amount_references = [
    ('GDP in United States','{times:,.2f} times the USA GDP','{percent:,.2f} percent of the USA GDP','1 /{fraction:,.0f} of the USA GDP'),
    ('GDP in China','{times:,.2f} times the China GDP','{percent:,.2f} percent of the China GDP','1 /{fraction:,.0f} of the China GDP'),
    ('Total value of all gold ever mined','{times:,.2f} times the value of all the gold ever mined','{percent:,.2f} percent of the value of all the gold ever mined','1 /{fraction:,.0f} of the value of all the gold ever mined'),
    ('GDP in United Kingdom','{times:,.2f} times the UK GDP','{percent:,.2f} percent of the UK GDP','1 /{fraction:,.0f} of the UK GDP'),
    ('GDP in Luxembourg','{times:,.2f} times the Luxembourg GDP','{percent:,.2f} percent of the Luxembourg GDP','1 /{fraction:,.0f} of the Luxembourg GDP'),
    ('Wealth of the wealthiest person in the world (Elon Musk 2022)','{times:,.2f} times the wealth of the wealthiest person','{percent:,.2f} percent of the wealth of the wealthiest person','1 /{fraction:,.0f} of the wealth of the wealthiest person'),
    ('Largest Win on a Lottery Ticket','{times:,.2f} times the largest-ever lottery win','{percent:,.2f} percent of the largest-ever lottery win (per ticket)','1 /{fraction:,.0f} of the largest-ever lottery win (per ticket)'),
    ('Highest price for a painting sold at auction','{times:,.2f} times the highest price paid for a painting','{percent:,.2f} percent of the highest price ever paid for a painting','1 /{fraction:,.0f} of the highest price ever paid for a painting'),
    ('Cost of making Avengers: Age of Ultron movie','{times:,.2f} times the cost of making Avengers: Age of Ultron movie','{percent:,.2f} percent of the cost of making Avengers: Infinity War movie','1 /{fraction:,.0f} of the cost of making Avengers: Infinity War movie'),
    ('Cost of Lamborghini Huracan Convertible car (2021)','{times:,.2f} times the cost of a Lamborghini Huracan Convertible car','{percent:,.2f} percent of the cost of a Lamborghini Huracan Spyder Convertible AWD car','1 /{fraction:,.0f} of the the cost of a Lamborghini Huracan Spyder Convertible AWD car'),
    ('Cost of Porsche Carrera 4S Coupe AWD car (2018)','{times:,.2f} times the cost of a Porsche Carrera 4S','{percent:,.2f} percent of the cost of a Porsche Carrera 4S','1 /{fraction:,.0f} of the the cost of a Porsche Carrera 4S'),
    ('Price of Boston Red Sox grandstand season ticket (2022)','{times:,.2f} times the cost of a Red Sox season ticket','{percent:,.2f} percent of the cost of a Red Sox season ticket','1 /{fraction:,.0f} of the the cost of a Red Sox season ticket'),
    ('Cost of iPhone 13 Pro Max - 256GB (2022)','{times:,.2f} times the cost of an iPhone 13 Pro Max','{percent:,.2f} percent of the cost of an iPhone XS/512GB','1 /{fraction:,.0f} of the the cost of an Cost of iPhone 13 Pro Max'),
    ('Price of a Big Mac hamburger in the United States (2022)','{times:,.2f} times the cost of a Big Mac in USA','{percent:,.2f} percent of the cost of a Big Mac in USA','1 /{fraction:,.0f} of the the cost of a Big Mac in USA'),
    ('Price of a Big Mac hamburger in Russia (2022)','{times:,.2f} times the cost of a Big Mac in Russia','{percent:,.2f} percent of the cost of a Big Mac in Russia','1 /{fraction:,.0f} of the the cost of a Big Mac in Russia'),
]

duration_references = [
    ('Age of the universe','{times:,.2f} times the age of the universe','{percent:,.2f} percent of the age of the universe','1 /{fraction:,.0f} of the age of the universe'),
    ('Age of the Earth','{times:,.2f} times the age of the Earth','{percent:,.2f} percent of the age of the Earth','1 /{fraction:,.0f} of the age of the Earth'),
    ('Time since the first modern humans','{times:,.2f} times the period since the emergence of the first modern humans','{percent:,.2f} percent of the time since the emergence of the first modern humans','1 /{fraction:,.0f} of the time since the emergence of the first modern humans'),
    ('Time since the building of Great Wall of China','{times:,.2f} times the period since the building of the Great Wall of China','{percent:,.2f} percent of the time since the building of the Great Wall of China','1 /{fraction:,.0f} of the time since the building of the Great Wall of China'),
    ('Lifespan of Galapagos giant tortoise','{times:,.2f} times the lifespan of a Galapagos giant tortoise','{percent:,.2f} percent of the lifespan of a Galapagos giant tortoise','1 /{fraction:,.0f} of the lifespan of a Galapagos giant tortoise'),
    ('One average human generation','{times:,.2f} human generations','{percent:,.2f} percent of a human generation','1 /{fraction:,.0f} of a human generation'),
    ('Lifespan of rat','{times:,.2f} times the lifespan of a rat','{percent:,.2f} percent of the lifespan of a rat','1 /{fraction:,.0f} of the lifespan of a rat'),
]

mass_references = [
    ('Mass of the Sun','{times:,.2f} times the mass of the Sun','{percent:,.2f} percent of the mass of the Sun','1 /{fraction:,.0f} of the mass of a domestic washing machine'),
    ('Mass of the Earth','{times:,.2f} times the mass of the Earth','{percent:,.2f} percent of the mass of the Earth','1 /{fraction:,.0f} of the mass of the Earth'),
    ('Mass of the Moon','{times:,.2f} times the mass of the Moon','{percent:,.2f} percent of the mass of the Moon','1 /{fraction:,.0f} of the mass of the Moon'),
    ('Mass of all the water in the Earth\'s seas','{times:,.2f} times the mass of all the water in the Earth\'s seas','{percent:,.2f} percent of the mass of all the water in the Earth\'s seas','1 /{fraction:,.0f} of the mass all the water in the Earth\'s seas'),
    ('Mass of all the Earth\'s biomass','{times:,.2f} times the mass of all the Earth\'s biomass','{percent:,.2f} percent of the mass of all the Earth\'s biomass','1 /{fraction:,.0f} of the mass of all the Earth\'s biomass'),
    ('Mass of all the humans on Earth','{times:,.2f} times the mass of all the humans on Earth','{percent:,.2f} percent of the mass of all the humans on Earth','1 /{fraction:,.0f} of the mass of all the humans on Earth'),
    ('Mass of the Great Pyramid of Giza','{times:,.2f} times the mass of the Great Pyramid of Giza','{percent:,.2f} percent of the mass of the Great Pyramid of Giza','1 /{fraction:,.0f} of the mass of the Great Pyramid of Giza'),
    ('Mass of the Titanic','{times:,.2f} times the mass of the Titanic','{percent:,.2f} percent of the mass of the Titanic','1 /{fraction:,.0f} of the mass of the Titanic'),
    ('Mass of an Airbus A380 airliner (max takeoff weight)','{times:,.2f} times the mass of an Airbus A380','{percent:,.2f} percent of the mass of an Airbus A380','1 /{fraction:,.0f} of the mass of an Airbus A380'),
    ('Mass of the Statue of Liberty','{times:,.2f} times the mass of the Statue of Liberty','{percent:,.2f} percent of the mass of the Statue of Liberty','1 /{fraction:,.0f} of the mass of the Statue of Liberty'),
    ('Mass of a Blue Whale','{times:,.2f} times the mass of a Blue Whale','{percent:,.2f} percent of the mass of a Blue Whale','1 /{fraction:,.0f} of the mass of a Blue Whale'),
    ('Mass of an M1 Abrams tank','{times:,.2f} times the mass of an M1 Abrams tank','{percent:,.2f} percent of the mass of an M1 Abrams tank','1 /{fraction:,.0f} of the mass of an M1 Abrams tank'),
    ('Mass of an adult male White Rhino','{times:,.2f} times the mass of a Rhino','{percent:,.2f} percent of the mass of a Rhino','1 /{fraction:,.0f} of the mass of a Rhino'),
    ('Mass of a small passenger car','{times:,.2f} times the mass of a small passenger car','{percent:,.2f} percent of the mass of a small passenger car','1 /{fraction:,.0f} of the mass of a small passenger car'),
    ('Mass of a concert grand piano','{times:,.2f} times the mass of a concert grand piano','{percent:,.2f} percent of the mass of a concert grand piano','1 /{fraction:,.0f} of the mass of a concert grand piano'),
    ('Mass of an adult male red kangaroo','{times:,.2f} times the mass of an adult male red kangaroo','{percent:,.2f} percent of the mass of an adult male red kangaroo','1 /{fraction:,.0f} of the mass of an adult male red kangaroo'),
    ('Mass of a domestic washing machine','{times:,.2f} times the mass of a domestic washing machine','{percent:,.2f} percent of the mass of a domestic washing machine','1 /{fraction:,.0f} of the mass of a domestic washing machine'),
    ('Mass of a large watermelon','{times:,.2f} times the mass of a large watermelon','{percent:,.2f} percent of the mass of a large watermelon','1 /{fraction:,.0f} of the mass of a large watermelon'),
    ('Mass of a brick','{times:,.2f} times the mass of a brick','{percent:,.2f} percent of the mass of a brick','1 /{fraction:,.0f} of the mass of a brick'),
    ('Mass of an iPad Air','{times:,.2f} times the mass of an iPad Air','{percent:,.2f} percent of the mass of an iPad Air','1 /{fraction:,.0f} of the mass of an iPad Air'),
    ('Mass of an iPhone 13 Pro','{times:,.2f} times the mass of an iPhone 7','{percent:,.2f} percent of the mass of an iPhone 7','1 /{fraction:,.0f} of the mass of an iPhone 13'),
    ('Mass of a BIC pen','{times:,.2f} times the mass of a BIC pen','{percent:,.2f} percent of the mass of a BIC pen','1 /{fraction:,.0f} of the mass of a BIC pen'),
    ('Mass of a USA penny (1c piece)','{times:,.2f} times the mass of a USA penny (1c)','{percent:,.2f} percent of the mass of a USA penny (1c)','1 /{fraction:,.0f} of the mass of a USA penny (1c)'),
]

energy_references = [
    ('Energy in boiling a kettle','{times:,.2f} times the energy used in boiling a kettle','{percent:,.2f} percent of the energy used in boiling a kettle','1 /{fraction:,.0f} of the energy used in boiling a kettle'),
]

capacity_references = [
    ('Volume of blood in an average human body','{times:,.2f} times the volume of blood in an average human body','{percent:,.2f} percent of the volume of blood in an average human body','1 /{fraction:,.0f} of the volume of blood in an average human body'),
]

reference_lists = {
    'ex': extent_references,
    'co': count_references,
    'am': amount_references,
    'du': duration_references,
    'ma': mass_references,
    'en': energy_references,
    'ca': capacity_references,
}


EXTENT_UNIT_CHOICES= (
        ('km', 'kilometer'),
        ('m', 'meter'),
        ('cm', 'centimeter'),
        ('mm', 'millimeter'),
        ('mile', 'mile'),
        ('yard', 'yard'),
        ('foot', 'foot'),
        ('inch', 'inch'),
    )

COUNT_UNIT_CHOICES= (
        ('i', 'item'),
    )

AMOUNT_UNIT_CHOICES= (
        ('USD', 'US Dollars (USD)'),
        ('AUD', 'Australian Dollar (AUD)'),
        ('CAD', 'Canadian Dollar (CAD)'),
        ('CHF', 'Swiss Franc (CHF)'),
        ('EUR', 'Euros (EUR)'),
        ('GBP', 'UK Pounds (GBP)'),
        ('HKD', 'Hongkong Dollar (HKD)'),
        ('JPY', 'Japanese Yen (JPY)'),
    )

DURATION_UNIT_CHOICES= (
        ('year', 'year'),
        ('month', 'month'),
        ('week', 'week'),
        ('day', 'day'),
        ('hour', 'hour'),
        ('minute', 'minute'),
        ('second', 'second'),
    )

MASS_UNIT_CHOICES= (
        ('t', 'metric_ton'),
        ('kg', 'kilogram'),
        ('g', 'gram'),
        ('ton', 'ton'),
#        ('cwt', 'hundredweight'),
        ('st', 'stone'),
        ('lb', 'pound'),
    )

ENERGY_UNIT_CHOICES= (
        ('J', 'joule'),
        ('erg', 'erg'),
        ('kWh', 'Kilowatt Hour'),
        ('MWh', 'Megawatt Hour'),
        ('GWh', 'Gigawatt Hour'),
        ('TWh', 'Terawatt Hour'),
        ('PWh', 'Petawatt Hour'),
        ('BTU', 'British Thermal Unit'),
        ('cal', 'Thermochemical calorie'),
        ('kcal', 'Food Calorie'),
    )

CAPACITY_UNIT_CHOICES= (
        ('mL', 'millilitre'),
        ('L', 'litre'),
        ('kL', 'Kilolitre'),
        ('ML', 'Megalitre'),
        ('imperial_pint', 'imperial pint'),
        ('imperial_gallon', 'imperial gallon'),
        ('pint', 'US pint'),
        ('gallon', 'US gallon'),
    )



unit_choice_lists = {
    'ex': EXTENT_UNIT_CHOICES,
    'co': COUNT_UNIT_CHOICES,
    'am': AMOUNT_UNIT_CHOICES,
    'du': DURATION_UNIT_CHOICES,
    'ma': MASS_UNIT_CHOICES,
    'en': ENERGY_UNIT_CHOICES,
    'ca': CAPACITY_UNIT_CHOICES,
}

all_unit_choices = EXTENT_UNIT_CHOICES + COUNT_UNIT_CHOICES + AMOUNT_UNIT_CHOICES + DURATION_UNIT_CHOICES + MASS_UNIT_CHOICES + ENERGY_UNIT_CHOICES + CAPACITY_UNIT_CHOICES

quip_lists = {
    "ex":(
        "It's a long, long way to ...",
        "Size matters ...",
        '"Shorth is better than length." Dr Seuss',
        '"Space is big. You just won\'t believe how vastly, hugely, mind-bogglingly big it is. I mean, you may think it\'s a long way down the road to the drug store, but that\'s just peanuts to space." Douglas Adams',
        ),
    "co":(
        "Let me count the ways ...",
        "It's the little things that count",
        "Not everything that can be counted counts",
        "Not everything that counts can be counted",
        "Shh ... I'm counting",
        ),
    "am":(
        "There's more to life than money",
        '"In school, my favorite subject was math. That\'s where I learned to count money"',
        'A nickel ain’t worth a dime anymore',
        '"Money money money, must be funny, in a rich man\'s world"'
        ),
    "du":(
        'How many years can a mountain exist?',
        'Eight Days a Week',
        'Don\'t just count your years, make your years count.',
        ),
    "ma":(
        'He ain\'t heavy ... ',
        ),
    "en":(
        'Full of beans ... ',
        ),
    "ca":(
        'I\'ll take a pint of that ... ',
        ),
}

subsets = {}

def choose_quote(tag):
    global subsets
    if tag not in subsets:
        subset = [quote[1] for quote in quotes if tag in quote[0]]
        subsets[tag] = subset
    return choice(subsets[tag])

quotes = [
        (['n', 's'], 'A number of things come to mind ...'),
        (['n', ], 'Let the numbers talk for themselves'),
        (['n', ], 'Hundreds and thousands'),
        (['n', ], 'There\'s safety in numbers'),
        (['n', ], 'Strength in numbers'),
        (['n', ], 'Let\'s run the numbers'),
        (['n', ], 'Let\'s see what the numbers say'),
        (['n', 's'], 'Sharpen your number sense'),
        (['n', ], 'Numbers count'),
        (['n', ], '"... a man with numbers can put your mind at ease." Paul Simon: When Numbers Get Serious'),
        (['n', ], '"Wherever there is number, there is beauty." Proclus (410-485 A.D.)'),
        (['n', ], '"Headlines twice the size of the events." John Galsworthy'),
        (['n', ], '"An optimist will tell you the glass is half-full; the pessimist, half-empty; and the engineer will tell you the glass is twice the size it needs to be"'),
        (['n', ], '"Numbers have an important story to tell. They rely on you to give them a voice." Stephen Few'),
        (['n', ], '"The price of light is less than the cost of darkness." Arthur C. Nielsen'),
        (['n', 's'], '"It’s easy to lie with statistics. It’s hard to tell the truth without statistics." Andrejs Dunkels'),
        (['n', 's'], '"It is easy to lie with statistics; it is easier to lie without them." Frederick Mosteller'),
        (['n', ], '"I love the big round numbers. The bigger and rounder they are, the more I love them." Alan Alda'),
        (['n', 's'], '"Errors using inadequate data are much less than those using no data at all." Charles Babbage'),
        (['n', ], '"And then kerjillions of stars start to shine ..." Laurie Anderson: My Eyes'),
        (['n', ], '"Two hundred forty million voices / Two hundred forty million names  ..." Laurie Anderson: My Eyes'),
        (['n', ], '"What are numbers, really? I\'ve been studying them for 50-odd years and I don\'t think I know." J H Conway'),
        (['n', ], '"Everything around you is mathematics. Everything around you is numbers." Shakuntala Devi'),
        (['n', ], '"Numbers have life; they\'re not just symbols on paper." Shakuntala Devi'),
        (['n', ], '"If we succeed in giving the love of learning, the learning itself is sure to follow." John Lubbock'),
        (['n', 's'], '"The things of this world cannot be made known without a knowledge of mathematics." Roger Bacon'),
        (['n', ], '"It took men about five thousand years, counting from the beginning of number symbols, to think of a symbol for nothing." Isaac Asimov'),
        (['n', 's'], '"Without numbers, we can understand nothing and know nothing" Philolaus'),
        (['n', ], '"Numbers constitute the only universal language."  Nathanael West'),
        (['n', 's'], '"An investment in knowledge pays the best interest." Benjamin Franklin'),
        (['n', ], '"The less one knows about the universe, the easier it is to explain." Leon Brunschvicg'),
        (['n', 's'], '"The book of nature is written in the language of Mathematics." Galileo'),
        (['n', 's'], '"Measure what is measurable, and make measurable what is not so." Galileo'),
        (['n', ], '"The computers are not replacing mathematicians; they are breeding them." Martin Gardner'),
        (['n', ], '"Mathematics is not only real, but it is the only reality." Martin Gardner'),
        (['n', ], '"Round numbers are always false." Samuel Johnson'),
        (['n', ], '"You have to be odd to be number one." Dr. Seuss'),
        (['n', ], '"When you can measure what you are speaking about, and express it in numbers, you know something about it" Lord Kelvin'),
        (['n', ], '"You don\'t need people’s opinion on a fact. You might as well have a poll asking: ‘Which number is bigger, 15 or 5?’" John Oliver'),
        (['n', ], '"My big thesis is that although the world looks messy and chaotic, if you translate it into the world of numbers and shapes, patterns emerge and you start to understand why things are the way they are". Marcus du Sautoy'),
        (['n', ], '"The hardest arithmetic to master is that which enables us to count our blessings." Eric Hoffer'),
        (['n', ], '[In] Astronomy, if you’re getting within 10 orders of magnitude, you’re okay." Sir Michael Atiyah'),
        (['n', ], '"When you have mastered numbers, you will in fact no longer be reading numbers, any more than you read words when reading books. You will be reading meanings." W.E.B. Du Bois'),
        (['n', ], '"Numbers are the masters of the weak, but the slaves of the strong." Charles Babbage'),
        (['n', ], '"You don\'t have to be a mathematician to have a feel for numbers." John Forbes Nash, Jr.'),
        (['n', ], '"Numbers are the musical notes with which the symphony of the universe is written" Adam Spencer'),
        (['n', ], '"The simplest schoolboy is now familiar with facts for which Archimedes would have sacrificed his life." Ernest Renan'),
        (['n', ], '"Facts are better than myths, especially for understanding the world." Hans Rosling'),
        (['n', 's' ], '"There\'s about one sword-swallower per 2 to 4 million persons in each country." Hans Rosling'),
        (['n', 's' ], '"My interest is not data, it\'s the world. And part of world development you can see in numbers. Others, like human rights, empowerment of women, it\'s very difficult to measure in numbers." Hans Rosling'),
        (['n', ], '"If numbers aren\'t beautiful, I don\'t know what is." Paul Erdos'),
        (['n', ], '"A mathematician, like a painter or poet, is a maker of patterns." G. H. Hardy'),
        (['n', ], '"The mathematician’s patterns, like the painter’s or the poet’s, must be beautiful; the ideas, like the colours or the words, must fit together in a harmonious way." G. H. Hardy'),
        (['n', ], '"I am accustomed, as a professional mathematician, to living in a sort of vacuum, surrounded by people who declare with an odd sort of pride that they are mathematically illiterate." David Mumford'),
        (['n', 's' ], '"It does not do to leave a live dragon out of your calculations, if you live near him." J. R. R. Tolkien'),
        (['n', ], '"Ford carried on counting quietly. This is about the most aggressive thing you can do to a computer." Douglas Adams'),
        (['n', ], '"Counting at the rate of one number per second, to count to a trillion takes 32,000 years, which is as much time as has elapsed since people first drew on cave walls." Neil deGrasse Tyson'),
        (['n', ], '"There are 350 varieties of shark, not counting loan and pool." L. M. Boyd'),
        (['n', ], '"Number is the ruler of forms and ideas, and the cause of gods and demons." Pythagoras'),
        (['n', ], '"Numbers are intellectual witnesses that belong only to mankind." Honore de Balzac'),
        (['n', 's' ], '"Anyone who attempts to generate random numbers by deterministic means is, of course, living in a state of sin." John von Neumann'),
        (['n', ], '"Where there is matter, there is geometry." Johannes Kepler'),
        (['n', ], '"\'Forty-two,\' said Deep Thought, with infinite majesty and calm." Douglas Adams'),
        (['n', ], '"There is wonder in the world, and it\'s an honour to be part of it." Adam Rutherford'),
        (['n', ], '"Science does not know its debt to imagination." Ralph Waldo Emerson'),
        (['n', ], '"Every culture has contributed to maths just as it has contributed to literature. It\'s a universal language; numbers belong to everyone." Daniel Tammet'),
        (['n', ], '"[Maths is] a universal language; numbers belong to everyone." Daniel Tammet'),
        (['n', ], '"Every culture has contributed to maths just as it has contributed to literature." Daniel Tammet'),
        (['n', ], '"I would play with numbers in a way that other kids would play with their friends." Daniel Tammet'),
        (['n', ], '"Human beings cannot comprehend very large or very small numbers. It would be useful for us to acknowledge that fact." Daniel Kahneman'),
        (['n', ], '"Counting in octal is just like counting in decimal, if you don\'t use your thumbs." Tom Lehrer'),
        (['n', 's' ], '"Numeracy isn\'t a sign of geekiness, but a basic requirement for intelligent discussions of public policy." Nicholas Kristof'),
        (['n', 's' ], '"If you think education is expensive, wait until you see how much ignorance costs." President Barack Obama'),
        (['n', 's' ], '"Measurement is the first step that leads to control and eventually to improvement. If you can’t measure something, you can’t understand it.” H. James Harrington'),
        (['n', ], '"Time is change; we measure its passing by how much things alter." Nadine Gordimer'),
        (['n', ], '"By any reasonable measure of achievement, the faith of the Enlightenment thinkers in science was justified." E. O. Wilson'),
        (['n', ], '"Be the measure great or small, let it be honest in every part." John Bright'),
        (['n', ], '"I measure in my palm and use my eyes to estimate amounts; a tablespoon is a full palm of dried spices." Rachael Ray'),
        (['n', ], '"Science cannot progress without reliable and accurate measurement of what it is you are trying to study." Robert D. Hare'),
        (['n', ], '"The heart of science is measurement." Erik Brynjolfsson'),
        (['n', ], '"I have been struck again and again by how important measurement is to improving the human condition." Bill Gates'),
        (['n', ], '"From science to business to education to economic policy, good decisions depend on good measurement." Ben Bernanke'),
        (['n', ], '"The wonder is, not that the field of the stars is so vast, but that man has measured it." Anatole France'),
        (['n', ], '"Our clocks do not measure time. ... Time is defined to be that which our clocks measure." Anonymous'),
        (['n', ], '"The first steps in the path of discovery, and the first approximate measures, are those which add most to the existing knowledge of mankind." Charles Babbage'),
        (['n', 's' ], '"Whenever you can, count." Sir Francis Galton'),
        (['n', ], '"Number, the most excellent of all inventions." Aeschylus'),
        (['n', 's' ], '"Statistician: A man who believes figures don\'t lie but admits that, under analysis some of them won\'t stand up either." Evan Esar'),
        (['n', ], '"The number of stars making up the Milky Way is about 10¹¹ or something like the number of raindrops falling in Hyde Park in a day’s heavy rain." Sir Jack Balwin'),
        (['n', ], '"Truly I say to you, a single number has more genuine and permanent value than an expensive library full of hypotheses." Robert Mayer'),
        (['n', 's' ], 'Benford\'s Law of Controversy: "Passion is inversely proportional to the amount of real information available." Gregory (Albert) Benford'),
        (['n', 's' ], '"It seems to me, that if statesmen had a little more arithmetic, or were accustomed to calculation, wars would be much less frequent." Benjamin Franklin'),
        (['n', ], '"Why speculate when you can calculate?" Anonymous'),
        (['n', ], '"Where does our success come from? The answer is synthesis, the ability to combine creativity and calculation, art and science, into whole that is much greater than the sum of its parts." Garry Kasparov'),
        (['n', ], '"A few drops of science will often disinfect an entire barrel full of ignorance and prejudice." Hendrik Willem van Loon'),
        (['n', ], '"The beauty of mathematics only shows itself to more patient followers." Maryam Mirzakhani'),
        (['n', ], '"It\'s not only the question, but the way you try to solve it." Maryam Mirzakhani'),
        (['n', ], '"Mathematics is the sister, as well as the servant, of the arts and is touched by the same madness and genius." Harold Marston Morse'),
        (['n', ], '"Life on Earth gives only a small taste of what can happen in the universe." Carlo Rovelli'),
        (['n', 's' ], '"Ever since we discovered that Earth is round and turns like a mad spinning-top, we have understood that reality is not as it appears to us." Carlo Rovelli'),
        (['n', ], '"Mathematics is the most beautiful and most powerful creation of the human spirit." Stefan Banach'),
        (['n', ], '"Mathematics is as old as Man." Stefan Banach'),
        (['n', ], '"Beauty is the first test: there is no permanent place in the world for ugly mathematics." G. H. Hardy'),
        (['n', ], '"The art and science of asking questions is the source of all knowledge". Thomas Berger'),
        (['n', ], '"Science literacy is the artery through which the solutions of tomorrow\'s problems flow." Neil deGrasse Tyson'),
        (['n', ], '"Equipped with his five senses, man explores the universe around him and calls the adventure Science." Edwin Powell Hubble'),
        (['n', ], '"Each problem that I solved became a rule, which served afterwards to solve other problems." Rene Descartes'),
        (['n', ], '"There are in fact two things, science and opinion; the former begets knowledge, the later ignorance." Hippocrates'),
        (['n', 's' ], '"The fewer the facts, the stronger the opinion." Arnold H. Glasow'),
        (['n', ], '"Science is magic that works." Kurt Vonnegut'),
        (['n', 's' ], '"Knowledge is like money: to be of value it must circulate, and in circulating it can increase in quantity and, hopefully, in value." Louis L\'Amour'),
        (['n', ], '"Being a track sprinter, when it\'s all about a thousandth of a second, there is no escaping the numbers every single day." Victoria Pendleton'),
        (['n', ], '"A lot of civilization is just learning to take advantage of water." Geoffrey Miller'),
        (['n', ], '"Coding is the most powerful medium of developing the sophisticated and rigorous thinking needed for mathematics, for grammar, for physics, for statistics, for all the "hard" subjects." Seymour Papert'),
        (['n', 's' ], '"I can think of no better tool than quantitative thinking to process the information that is thrown at me." Rebecca Goldin'),
        (['n', ], '"We must say that there are as many squares as there are numbers." Galileo Galilei'),
        (['n', 's' ], '"Data allow your political judgments to be based on fact, to the extent that numbers describe realities." Hans Rosling'),
        (['n', ], '"There is strength in numbers, but organizing those numbers is one of the great challenges." John C. Mather'),
        (['n', 's' ], '"On average, people should be more skeptical when they see numbers. They should be more willing to play around with the data themselves." Nate Silver'),
        (['n', ], '"Pure mathematics is, in its way, the poetry of logical ideas." Albert Einstein'),
        (['n', ], '"Mathematics is the music of reason." James Joseph Sylvester'),
        (['n', ], '"To me, mathematics, computer science, and the arts are insanely related. They\'re all creative expressions." Sebastian Thrun'),
        (['n', ], '"Mathematics knows no races or geographic boundaries; for mathematics, the cultural world is one country." David Hilbert'),
        (['n', ], '"I\'ve always enjoyed mathematics. It is the most precise and concise way of expressing any idea." N. R. Narayana Murthy'),
        (['n', ], '"The definition of a good mathematical problem is the mathematics it generates rather than the problem itself." Andrew Wiles'),
        (['n', 's' ], '"Explore the world. Nearly everything is really interesting if you go into it deeply enough." Richard Feynman'),
        (['n', ], '"A man only becomes wise when he begins to calculate the approximate depth of his ignorance." Gian Carlo Menotti'),
        (['n', ], '"Arithmetic! Algebra! Geometry! Grandiose trinity! Luminous triangle! Whoever has not known you is without sense!" Comte de Lautreamont'),
        (['n', 's' ], '"He who refuses to do arithmetic is doomed to talk nonsense." John McCarthy'),
        (['n', ], '"Computers are better than we are at arithmetic, not because computers are so good at it, but because we are so bad at it." Isaac Asimov'),
        (['n', ], '"I have no satisfaction in formulas unless I feel their arithmetical magnitude." Lord Kelvin'),
        (['n', 's' ], '"[the good of counting is that] it brings every thing to a certainty, which before floated in the mind indefinitely." Samuel Johnson'),
        (['n', ], '"A googleplex is precisely as far from infinity as is the number 1 ... No matter what number you have in mind, infinity is larger." Carl Sagan'),
        (['n', ], '"All the mathematical sciences are founded on relations between physical laws and laws of numbers, so that the aim of exact science is to reduce the problems of nature to the determination of quantities by operations with numbers." James Clerk Maxwell'),
        (['n', ], '"The judicial mind is too commonly characterized by a regard for a fourth decimal as the equal of a whole number." Martin H. Fischer'),
        (['n', ], '[On why are numbers beautiful?] "It’s like asking why is Beethoven’s Ninth Symphony beautiful. If you don’t see why, someone can’t tell you. I know numbers are beautiful. If they aren’t beautiful, nothing is." Paul Erdös'),
        (['n', ], '"Mathematics has a threefold purpose. It must provide an instrument for the study of nature. But this is not all: it has a philosophical purpose, and, I daresay, an aesthetic purpose." Henri Poincaré'),
        (['n', ], '"As history proves abundantly, mathematical achievement, whatever its intrinsic worth, is the most enduring of all." G. H. Hardy'),
        (['n', ], '"Do not imagine that mathematics is harsh and crabbed, and repulsive to common sense. It is merely the etherealisation of common sense." Lord Kelvin'),
        (['n', ], '"I am ever more intrigued by the correspondence between mathematics and physical facts. The adaptability of mathematics to the description of physical phenomena is uncanny." Nicolaas Bloembergen'),
        (['n', ], '"One can argue that mathematics is a human activity deeply rooted in reality, and permanently returning to reality." Yuri I. Manin'),
        (['n', ], '"Uniformity in the currency, weights, and measures of the United States is an object of great importance, and will, I am persuaded, be duly attended to." George Washington'),
        (['n', 's' ], '"[In plotting earthquake measurements] the range between the largest and smallest magnitudes seemed unmanageably large. Dr. Beno Gutenberg then made the natural suggestion to plot the amplitudes logarithmically." Charles Richter'),
        (['n', ], '"Anecdotes are not data but one data point is a hell of a lot better than zero data points." Eliezer Yudkowsky'),
        (['n', ], '"Everything you’ve learned in school as \'obvious\' becomes less and less obvious as you begin to study the universe." Richard Buckminster Fuller'),
        (['n', ], '"The basis for poetry and scientific discovery is the ability to comprehend the unlike in the like and the like in the unlike." Jacob Bronowski'),
        (['n', 's' ], '"Be suspicious of anything that works perfectly - it\'s probably because two errors are canceling each other out." Dave Bartley'),
        (['n', ], '"An educated mind is, as it were, composed of all the minds of preceding ages." Le Bovier de Fontenelle'),
        (['n', ], '"We especially need imagination in science. It is not all mathematics, nor all logic, but it is somewhat beauty and poetry." Maria Mitchell'),
        (['n', ], '"Mathematics is one of the surest ways for a man to feel the power of thought and the magic of the spirit." Malba Tahan'),
        (['n', ], '"There is no absolute scale of size in nature, and the small may be as important, or more so, than the great." Oliver Heaviside'),
        (['n', ], '"Science, like art, music and poetry, tries to reduce chaos to the clarity and order of pure beauty." DW Bronk'),
        (['n', ], '"The important thing in science is not so much to obtain new facts as to discover new ways of thinking about them." William L Bragg'),
        (['n', ], '"Nothing is more powerful for your future than being a gatherer of good ideas and information. That’s called doing your homework." Jim Rohn'),
        (['n', ], '"Doing mathematics should always mean finding patterns and crafting beautiful and meaningful explanations." Paul Lockhart'),
        (['n', ], '"It is not the job of mathematicians ... to do correct arithmetical operations. It is the job of bank accountants." Samuil Shatunovsky'),
        (['n', ], '"The scientist does not study nature because it is useful; he studies it because he delights in it." H Poincare'),
        (['n', ], '"The scientist does not study nature because it is useful to do so. He studies it because he takes pleasure in it, and he takes pleasure in it because it is beautiful." H Poincare'),
        (['n', ], '"If nature were not beautiful it would not be worth knowing, and life would not be worth living." H Poincare'),
        (['n', ], '"Time exists in order that everything doesn’t happen all at once, and space exists so that it doesn’t all happen to you." Susan Sontag'),
        (['n', ], '"One measure of our understanding is the number of independent ways we are able to get to the same result." Richard Feynman'),
        (['n', ], '"The mathematical sciences particularly exhibit order symmetry and limitations; and these are the greatest forms of the beautiful." Aristotle'),
        (['n', ], '"Measurement is the link between mathematics and science." Brian Ellis'),
        (['n', 's' ], '"Statistical thinking will one day be as necessary for efficient citizenship as the ability to read and write." H G Wells'),
        (['n', ], '"Mathematics is a way of thinking, a language that allows us to translate the complexity of the world into manageable patterns." KC Cole'),
        (['n', ], '"Unless a thing can be defined by measurement, it has no place in a theory." Richard Feynman'),
        (['n', ], '"The moving power of mathematical invention is not reasoning but imagination." Augustus de Morgan'),
        (['n', ], '"Beauty in mathematics is seeing the truth without effort." George Polya'),
        (['n', 's' ], '"I don\'t pretend we have all the answers. But the questions are certainly worth thinking about." Arthur C. Clarke'),
        (['n', 's' ], '"The science of probability gives mathematical expression to our ignorance, not to our wisdom." Samuel R Delany'),
        (['n', ], '"A good math puzzle, paradox, or magic trick can stimulate a child’s #imagination much faster than a practical application." Martin Gardner'),
        (['n', ], '"Mathematics, rightly viewed, possesses not only truth but also supreme beauty - a beauty ... like that of sculpture." Bertrand Russell'),
        (['n', 's' ], '"There is a single light of science, and to brighten it anywhere is to brighten it everywhere." Isaac Asimov '),
        (['n', ], '"... without at least an elementary instruction in mathematics and science, man will remain a stranger in this world" Ernst Mach'),
        (['n', 's' ], '"The world is full of magical things patiently waiting for our wits to grow sharper." Bertrand Russell'),
        (['n', ], '"The true spirit of delight, the exaltation, the sense of being more than Man, which is the touchstone of the highest excellence, is to be found in mathematics as surely as poetry." Bertrand Russell'),
        (['n', ], '"Even if the open windows of science at first make us shiver ... in the end, the fresh air brings vigor, and the great spaces have a splendor of their own." Bertrand Russell'),
        (['n', ], '"People who think they know everything are a great annoyance to those of us who do." Isaac Asimov'),
        (['n', 's' ], '"If knowledge can create problems, it is not through ignorance that we can solve them." Isaac Asimov'),
        (['n', 's' ], '"The most exciting phrase to hear in science, the one that heralds new discoveries, is not \'Eureka!\' but \'That\'s funny...\' Isaac Asimov'),
        (['n', ], '"Humanity has the stars in its future, and that future is too important to be lost under the burden of juvenile folly and ignorant superstition." Isaac Asimov'),
        (['n', ], '"We are a way for the Cosmos to know itself" Carl Sagan'),
        (['n', ], '"As for everything else, so for a mathematical theory: beauty can be perceived but not explained." Arthur Cayley'),
        (['n', ], '"My goal is simple. It is a complete understanding of the universe, why it is as it is and why it exists at all." Stephen Hawking'),
        (['n', ], '"The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge." Stephen Hawking'),
        (['n', ], '"We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the universe. That makes us something very special." Stephen Hawking'),
        (['n', ], '"As bad as we are at remembering names and phone numbers ..., we have really exceptional visual and spatial memories." Joshua Foer'),
        (['n', ], '"We don\'t have parades for mathematicians, we have parades for astronauts. You don\'t think about all the thousands of people who worked on that capsule and crunched the numbers and were integral in getting that into space." Theodore Melfi'),
        (['n', ], '"We find them smaller and fainter, in constantly increasing numbers, and we know that we are reaching into space, farther and farther, until, with the faintest nebulae that can be detected with the greatest telescopes, we arrive at the frontier of the known universe." Edwin Powell Hubble'),
        (['n', ], '"There are two types of claims: those based on hard numbers and those based on slippery numbers." Simon Sinek'),
        (['n', ], '"I learned quickly, as I tell my graduate students now, there are no answers in the back of the book when the equipment doesn\'t work or the measurements look strange." Martin Lewis Perl'),
        (['n', 's' ], '"To understand numbers you first have to look at their relationship with each other." Anthony T. Hincks'),
        (['n', 's' ], '"It is given to us to calculate, to weigh, to measure, to observe, this is natural philosophy; almost all the rest is chimera." Voltaire'),
        (['n', ], '"There is not much difference between the delight a novice experiences in cracking a clever brain teaser and the delight a mathematician experiences in mastering a more advanced problem" Martin Gardner'),
        (['n', ], '"Whoever despises the high wisdom of mathematics nourishes himself on delusion" Leonardo da Vinci'),
        (['n', ], '"He who loves practice without theory is like a seafarer who boards ship without wheel or compass and knows not wither he travels." Leonardo da Vinci'),
        (['n', ], '"Just as iron rusts from disuse and stagnant water putrefies, or when cold turns to ice, so our intellect wastes unless it is kept in use." Leonardo da Vinci'),
        (['n', 's' ], '"Most people would die sooner than think – in fact they do so." Bertrand Russell'),
        (['n', ], '"It is true that a mathematician who is not also something of a poet will never be a perfect mathematician." Karl Weierstrass'),
        (['n', ], '"All of science comes from people noticing interesting side paths. You’ve got to have a very flexible approach to exploration and allow different people to try different things." Michael Atiyah'),
        (['n', ], '"We as mathematicians don’t have to be apologetic about saying we like beautiful things. We live on beautiful things." Sir Michael Atiyah'),
        (['n', ], '"It is no good to try to stop knowledge from going forward. Ignorance is never better than knowledge.", Enrico Fermi'),
        (['n', ], '"Mathematics is the fruitful Parent of, I had almost said all, Arts, the unshaken Foundation of Sciences, and the plentiful Fountain of Advantage to Human Affairs", Isaac Barrow'),       
        (['n', ], '"Life it is not just a series of calculations and a sum total of statistics, it\'s about experience, it\'s about participation, it is something more complex and more interesting than what is obvious." Daniel Libeskind'),
        (['n', 's' ], '"Cognitive psychology tells us that the unaided human mind is vulnerable to many fallacies and illusions because of its reliance on its memory for vivid anecdotes rather than systematic statistics." Steven Pinker'),
        (['n', 's' ], '"Statistics: the mathematical theory of ignorance". Morris Kline'),
        (['n', 's' ], '"I couldn\'t claim that I was smarter than sixty-five other guys--but the average of sixty-five other guys, certainly!" Richard Feynman'),
        (['n', 's' ], '"We must become more comfortable with probability and uncertainty". Nate Silver'),
        (['n', ], '"Mathematics has beauty and romance. It\'s not a boring place to be, the mathematical world. It\'s an extraordinary place; it\'s worth spending time there." Marcus du Sautoy'),
        (['n', ], '"The traditional mathematician recognizes and appreciates mathematical elegance when he sees it. I propose to go one step further, and to consider elegance an essential ingredient of mathematics: if it is clumsy, it is not mathematics." Edsger Dijkstra'),
        (['n', ], '"No matter how correct a mathematical theorem may appear to be, one ought never to be satisfied that there was not something imperfect about it until it also gives the impression of being beautiful." George Boole'),
        (['n', ], '"Music rhythms are mathematical patterns. When you hear a song and your body starts moving with it, your body is doing math. The kids in their parents\' garage practicing to be a band may not realize it, but they\'re also practicing math." Kareem Abdul-Jabbar'),
        (['n', ], '"One of the pleasures of looking at the world through mathematical eyes is that you can see certain patterns that would otherwise be hidden." Steven Strogatz'),
        (['n', ], '"Mathematics expresses values that reflect the cosmos, including orderliness, balance, harmony, logic, and abstract beauty." Deepak Chopra'),
        (['n', ], '"Mathematics is the cheapest science. Unlike physics or chemistry, it does not require any expensive equipment. All one needs for mathematics is a pencil and paper." George Polya'),
        (['n', ], '"Mathematics and poetry are the two ways to drink the beauty of truth." Amit Ray'),
        (['n', ], '"To raise new questions, new possibilities, to regard old problems from a new angle, requires creative imagination and marks real advance in science". Albert Einstein'),
        (['n', ], '"I am among those who think that science has great beauty." Marie Curie'),
        (['n', 's' ], '"Nothing has such power to broaden the mind as the ability to investigate systematically and truly all that comes under thy observation in life." Marcus Aurelius'),
        (['n', 's' ], '"Science, my lad, is made up of mistakes, but they are mistakes which it is useful to make, because they lead little by little to the truth." Jules Verne'),
        (['n', ], '"Science is not everything, but science is very beautiful." J. Robert Oppenheimer'),
        (['n', ], '"Mathematical science shows what is. It is the language of unseen relations between things. But to use and apply that language, we must be able fully to appreciate, to feel, to seize the unseen, the unconscious." Ada Lovelace'),
        (['n', ], '"You never change things by fighting the existing reality. To change something, build a new model that makes the existing model obsolete." R. Buckminster Fuller'),
        (['n', ], '"When I am working on a problem, I never think about beauty but when I have finished, if the solution is not beautiful, I know it is wrong." R. Buckminster Fuller'),
        (['n', 's' ], '"Nature uses only the longest threads to weave her patterns, so that each small piece of her fabric reveals the organization of the entire tapestry." Richard P. Feynman'),
        (['n', 's' ], '"For 13 to be unlucky would require there to be some kind of cosmic intelligence that counts things that humans count and that also makes certain things happen on certain dates or in certain places according to whether the number 13 is involved." Douglas Hofstadter'),
        (['n', ], '"The greatest mathematicians, as Archimedes, Newton, and Gauss, always united theory and applications in equal measure." Felix Klein'),
        (['n', ], '"Mathematicians stand on each other\'s shoulders." Carl Friedrich Gauss'),
        (['n', ], '"The problem of distinguishing prime numbers from composite numbers and of resolving the latter into their prime factors is known to be one of the most important and useful in arithmetic." Carl Friedrich Gauss'),
        (['n', ], '"Only those who attempt the absurd will achieve the impossible. I think it\'s in my basement... let me go upstairs and check." M. C. Escher'),
        (['n', ], '"Many persons who have not studied mathematics confuse it with arithmetic and consider it a dry and arid science. Actually, however, this science requires great fantasy." Sophia Kovalevsky'),
        (['n', 's' ], '"Mathematics is a wonderful, mad subject, full of imagination, fantasy, and creativity  that is not limited by the petty details of the physical world, but only by the strength of our inner light." Gregory Chaitin'),


    ]


extent_conversion_targets = [
    ('kilometer'),
    ('metre'),
    ('millimeter'),
    ('mile'),
    ('yard'),
    ('foot'),
    ('inch'),
]

amount_conversion_targets = [
    ('USD'),
    ('AUD'),
    ('CAD'),
    ('CHF'),
    ('CNY'),
    ('INR'),
    ('RUB'),
    ('EUR'),
    ('GBP'),
    ('HKD'),
    ('JPY'),
]

duration_conversion_targets = [
    ('year'),
    ('month'),
    ('fortnight'),
    ('week'),
    ('day'),
    ('hour'),
    ('minute'),
    ('second'),
]


mass_conversion_targets = [
        ('metric_ton'),
        ('kilogram'),
        ('gram'),
        ('ton'),
 #       ('hundredweight'),
        ('stone'),
        ('pound'),
]

capacity_conversion_targets = [
        ('L'),
        ('ml'),
        ('imperial_pint'),
        ('imperial_gallon'),
        ('pint'),
        ('gallon'),
]

conversion_target_lists = {
    'ex': extent_conversion_targets,
    'am': amount_conversion_targets,
    'du': duration_conversion_targets,
    'ma': mass_conversion_targets,
    'ca': capacity_conversion_targets,
}

conversion_quip_lists = {
    "ex":("The long and winding road ...",),
    "am":("Money makes the world go round ...",),
    "du":("How long has it been ...",),
    "ma":("That\'s massive ...",),
    "ca":("Deep ...",),
}

MEASURE_CHOICES = (
    ('co', 'count'),
    ('am', 'amount'),
    ('ex', 'extent'),
    ('du', 'duration'),
    ('nu', 'number'),
    ('ma', 'mass'),
    ('ar', 'area'),
    ('vo', 'volume'),
    ('en', 'energy'),
    ('ca', 'capacity'),
)

MULTIPLE_CHOICES = (
    ('U', '-'),
    ('k', 'thousand'),
    ('M', 'million'),
    ('G', 'billion'),
    ('T', 'trillion'),
    ('P', 'quadrillion'),
    ('E', 'quintillion'),
    ('Z', 'sextillion'),
    ('Y', 'septillion'),
    ('10^27', '10^27'),
    ('10^30', '10^30'),
    ('10^33', '10^33'),
    ('10^36', '10^36'),
    ('10^39', '10^39'),
    ('10^42', '10^42'),
)

MULTIPLE_INVERSE = {
    -3:'m',
    0:'U',
    3:'k',
    6:'M',
    9:'G',
    12:'T',
    15:'P',
    18:'E',
    21:'Z',
    24:'Y',
    27:'10^27',
    30:'10^30',
    33:'10^33',
    36:'10^36',
    39:'10^39',
    42:'10^42',
}
